[ADD]account_more_invoice_space: reduce blank space below header and body's font size
bmya/odoo-bmya pull request #39
Opened 2024-03-26 01:49 UTC by jmo-bmya

Change pt-5 on standard and boxed layouts, and mt-5 on the invoice PDF template to pt-0 and mt-0 respectively.

Reduce font size to 80% on the invoice body

2024-03-26 01:51 UTC, jmo-bmya commented
@Danisan cómo le ponemos al módulo? Me gusta más el primero, aunque no lleva ningún prefijo con el nombre de un módulo de Odoo.

more_invoice_space
account_more_invoice_space
account_invoice_something (se aceptan sugerencias)

2024-04-22 18:34 UTC, Danisan requested changes
@jmo-bmya small change

2024-04-22 18:34 UTC, Danisan commented on account_more_invoice_space/__manifest__.py
> +    'version': '1.0.0',
```suggestion
    'version': '16.0.1.0.0',
```

2024-05-05 14:25 UTC, Danisan approved these changes

2024-05-05 14:26 UTC, Danisan approved these changes

2024-05-05 14:26 UTC, merged